### ISSUE TITLE
QR Scanner for Angularjs

### ISSUE THREAD

**Issue by mariusvdw** [gokulkrishh/gokulkrishh#3]
Hi Gokul,

What a brilliant QR scanner you have build.

I would like to include in in a Angularjs web app. Would that be possible?

**Comment by gokulkrishh** [comment]
@mariusvdw Glad, you like it 👍 . Yes, it's a simple web app that is built using vanilla js. you can include it in any web app. Feel free to fork and explore.

**Comment by 3dgiftz** [comment]
Awesome
